netguru/props

- app/models/user.rb
- db/migrate/20151217083621_add_unique_index_to_users.rb
- db/schema.rb
> Add users unique validation

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/docker_production.rb
- config/deploy/production.rb
- docker/production/Dockerfile
- docker/production/entrypoint.sh
This PR allows to deploy this app using Docker
> Docker deployment

- spec/factories/users.rb
generate guid in user factory so all of our tests pass
> Fix user factory

- Gemfile
- Gemfile.lock
> use haml_coffee_assets in a version which doesn't break with Rails 4.2.5.1

- app/react/components/user/user-props-container.jsx
- app/react/components/user/user-props.jsx
Pull given/received count from propsCount.
While props are paginated we can’t relay on sizes.
> user stats fix

- README.md
> Remove misleading, unneeded "Common problems/bugs" section from README

- app/models/prop.rb
- config/locales/en.yml
- spec/repositories/props_repository_spec.rb
Check if there is @here or @channel used in prop body.
> Prop body validation

- app/react/components/user/user-props.jsx
Given props count was displayed as received props count.
> Fix user stats

- app/controllers/api/v1/entities/prop.rb
React will escape dangerous html by default
> Dont sanitize body

- app/react/components/props/prop.jsx
> Temporary fix for inconsistent camelization of createdAt/created_at prop property

- app/controllers/api/v1/entities/user_full.rb
- app/react/components/user/user-props-container.jsx
- app/react/components/user/user-props-stats.jsx
- app/react/components/user/user-props.jsx
- app/repositories/users_repository.rb
- spec/repositories/users_repository_spec.rb
Archived users are still in app and it's possible to access their profile page.
> show archived user

- app/controllers/api/v1/base.rb
- app/controllers/api/v1/helpers.rb
- app/controllers/application_controller.rb
- spec/requests/api/v1/props_spec.rb
- spec/requests/api/v1/users_spec.rb
- spec/support/shared_api_contexts.rb
Description:
- fix base_path swagger configuration
- add api_user to authentication - user easy token owner as current user
> Api docs fix & api user access 

- config/sidekiq.yml
> Add queues info to sidekiq config

- app/assets/stylesheets/components/_props_list.scss
- app/react/actions/props.js
- app/react/components/PropsList/Prop.jsx
- app/react/components/PropsList/Vote.jsx
- app/react/components/PropsList/__tests__/props.test.jsx
- app/react/components/PropsList/__tests__/vote.test.jsx
- app/react/components/PropsList/index.jsx
- app/react/components/UsersList/User.jsx
- app/react/components/navbar/navbar.jsx
- app/react/containers/PropsList/index.js
Changes:
- display prop raiting 
- upvote a prop
- undo upvote a prop
- validate if upvote possible
- display current ranking
> PROP-10 Upvote prop

- app/assets/stylesheets/components/_props_list.scss
- app/assets/stylesheets/components/_user_card.scss
- app/react/actions/users.js
- app/react/components/UsersList/Profile.jsx
- app/react/components/UsersList/Thumb.jsx
- app/react/components/UsersList/ThumbSmall.jsx
- app/react/components/UsersList/__tests__/Thumb.test.jsx
- app/react/components/UsersList/__tests__/ThumbSmall.test.jsx
- app/react/components/UsersList/index.jsx
- app/react/constants/users.js
- app/react/containers/UsersList/User.js
- app/react/containers/UsersList/index.js
- app/react/reducers/index.js
- app/react/reducers/usersQuery.js
- app/react/routes/index.jsx
PROP-11
Changes:
Refactor a bit already existing components and display searchable list of users. Every user links to user profile.
> add basic users list with filtering

- README.md
- bin/setup
- db/seeds.rb
currently it’s not possible to setup the app using `bin/rails` command - this PR solves it
> simplify app setup

- README.md
Added Slack verification token info in README.
https://netguru.atlassian.net/browse/PROP-55
> PROP-55 Update readme with verification token info

- app/services/slack_commands/kudos.rb
- spec/requests/api/v1/slack_commands_spec.rb
Fixed issue with slash command regex allowing (-._) in usernames.
https://netguru.atlassian.net/browse/PROP-58
> PROP-58 Fix slash command regex issue

- Gemfile
- Gemfile.lock
- circle.yml
- spec/rails_helper.rb
Added rspec tests to circle
Removed scrutinizer integration.
Fixed codeclimate reporter.
https://netguru.atlassian.net/browse/PROP-59
> Prop 59 add circle rspec tests

- config/deploy/production.rb
Remove docker volume for secrets.yml on production
https://netguru.atlassian.net/browse/PROP-60
> Remove docker volume for secrets.yml

- app/models/user.rb
- app/repositories/users_repository.rb
- app/services/users/sign_in.rb
- spec/repositories/users_repository_spec.rb
Create or update user upon login with slack.
- Move updating user to user model
- Remove duplicated code
- Test functionality
> Prop-66 Update user upon login

- app/assets/stylesheets/components/_props_form.scss
- app/react/components/PropsList/__tests__/UserAvatar.test.jsx
- app/react/components/UsersList/Thumb.jsx
- app/react/components/UsersList/__tests__/Thumb.test.jsx
- Use avatars component
- Adjust styles
> PROP-75 Fix overlaying avatars

- app/controllers/api/v1/helpers.rb
- app/controllers/api/v1/slack_commands.rb
- config/locales/en.yml
- spec/requests/api/v1/slack_commands_spec.rb
Check if request is send with proper user agent
> Prop-68 Disallow user to change uid (bug)

- app/controllers/api/v1/users.rb
- app/jobs/download_users_job.rb
- config/locales/en.yml
- spec/jobs/download_users_job_spec.rb
- spec/requests/api/v1/users_spec.rb
Process fetching users from slack in the background.
> Prop-79 background users fetching

- .rubocop.yml
- README.md
- docker/production/Dockerfile
Bump ruby version to assert consistency between environments.
> Bump ruby version from 2.2.3 to 2.3.1

- lib/tasks/users.rake
Fix bug which occurred after `ArchiveUser` service refactoring
> PROP-82 Call archiver using keyword argument

- spec/lib/tasks/bundler_audit_spec.rb
- spec/lib/tasks/email_digests_spec.rb
- spec/lib/tasks/organisations_spec.rb
- spec/lib/tasks/users_spec.rb
- spec/support/shared_contexts/rake.rb
I simply added specs for rake tasks to make this app better, no big deal :)
> Add rake tasks specs

- app/models/prop.rb
> Increase props receivers limit

- .circleci/config.yml
- docker/production/Dockerfile
- docker/staging/Dockerfile
> Revert "[BN-996] Update docker image vulnerabilities "
