- app/assets/javascripts/backbone/entities/prop.coffee
props.queryParams are populated by Backbone.Pagable so it should not be replaced with filters.
> Pagination fix

- app/controllers/api/v1/props.rb
There should be pagination on given/received props on user page. For now, let's return all props when `propser_id` param specified and no `page` param specified
> don't paginate when there is no page param

- app/services/notifier/slack_notifier.rb
Right now there's sad, grey-coloured robot. PropsApp bot should not be sad at all.
> Set bot icon

- package.json
Heroku provides us with possibly to define dedicated `heroku-postbuild` script in `package.json` file - let's use it, and actually force manual building of assets by `npm run build` (already described in README file).
Potential hurdles:
* Would be nice to actually try pushing to Heroku before merging - weird stuff happens, let's make sure it doesn't happen to us.
* We actually need `postinstall` script, as its used for something else than Heroku (what exactly? - thinking about Docker setup that may need altering, perhaps).
> Use Heroku-specific "heroku-postbuild" script instead of generic "postinstall" hook

- README.md
- app/notifications/new_prop_notification.rb
- spec/notifications/new_prop_notification_spec.rb
- spec/rails_helper.rb
- Add space before and after underscore sign when posting slack notification
- If someone adds link to his prop and app will end his url with `_` sign, this link won't work.
> Fix broken urls in props

- config/initializers/rollbar.rb
Implemented to solve [this problem](https://netguru.atlassian.net/browse/SUP-1542). Those errors needlessly eat our quota, so they should be ignored.
> dont send 404 errors to rollbar

- app/services/notifier/slack_notifier.rb
> remove slack notifier options, so the main app icon is shown

- bin/setup
Fixed typo in Postgre user setup command. Changed `creatuser` to `createuser` command.
https://netguru.atlassian.net/browse/PROP-55
> PROP-55 Fix typo in setup file command

- .dockerignore
- Capfile
- config/deploy/production.rb
- docker/production/Dockerfile
- docker/staging/Dockerfile
Staging is currently using yarn install and working properly. Production is currently using npm install (should probably use yarn). After deploying on production there is a problem with building react_bundle.css and some dependencies errors. This will check if the problem lies in mixed up dependencies, by hopefully breaking the staging. 
NOTE: This must be reversed or production deploy file must be changed in order to work properly on production.
> PROP-57 Production missing react_bundle.css fix

- app/controllers/api/v1/entities/user_base.rb
- app/models/user.rb
- db/migrate/20170601204451_add_avatar_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/repositories/users_repository_spec.rb
- spec/support/omniauth_helpers.rb
Save url to slack avatar upon login
- Add db column for avatar url
- Save avatar upon login
- Serialize saved avatar OR gravatar if there is no avatar saved
- Test functionality
> Prop 67 store slack avatar

- app/models/user.rb
- spec/repositories/users_repository_spec.rb
- spec/support/omniauth_helpers.rb
Production bug fix - use small avatar when big isn't present. When both are nil use gravatar (already implemented in `user_base` but required changes in user attributes).
> Assign small avatar when big is blank

- app/controllers/api/v1/helpers.rb
- app/controllers/api/v1/users.rb
- app/models/user.rb
- app/repositories/users_repository.rb
- app/services/users/download_users.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users_spec.rb
- spec/services/users/download_users_spec.rb
- spec/support/omniauth_helpers.rb
Allow admin of the Slack organisation to update all users to the state from Slack - emails, avatars, names etc. Feature uses Slack API to request that data. Bot users are not being saved.
> Prop-69 Update all users in organisation

- app/controllers/api/v1/users.rb
- app/services/users/download_users.rb
- spec/requests/api/v1/users_spec.rb
- spec/services/users/download_users_spec.rb
- spec/support/omniauth_helpers.rb
Now during downloading users from slack organisation we save also guest users - this PR allow screening them out.
Admin verification is turned off for easier testing on real data on staging.
> Prop-77 screen out guests

- app/services/users/create_from_slack_fetch.rb
- spec/services/users/create_from_slack_fetch_spec.rb
- spec/support/omniauth_helpers.rb
Use smaller avatar when bigger is not available - info from Slack organisation
> Prop-78 Use smaller avatar when bigger is not available

- app/models/user.rb
- app/repositories/users_repository.rb
- app/services/users/create_from_omniauth.rb
- app/services/users/create_from_slack_fetch.rb
- spec/services/users/create_from_omniauth_spec.rb
- spec/services/users/create_from_slack_fetch_spec.rb
- spec/services/users/download_users_spec.rb
- spec/support/omniauth_helpers.rb
After integrating signing in with Slack, few users experienced a bug - creation of new account. It occurs when user was using different email address during previous integration with google. To solve this issue I change matching user to check email address but without domain.
Changes implemented in signing in process and users fetch process.
Some legacy code deleted.
> Prop-81 match email without domain

- app/services/users/create_from_omniauth.rb
- app/services/users/create_from_slack_fetch.rb
logs on production:
```
/var/www/app/app/services/users/create_from_omniauth.rb:29: syntax error, unexpected '.'
auth['info']['email']&.split('@')&.first
> Fix try error

- .rubocop.yml
Rubocop required `Missing magic comment # frozen_string_literal: true.` - turn it off
> PROP-84 Turn off magic comment rule

- app/controllers/api/v1/users.rb
- app/views/settings/index.html.haml
- spec/requests/api/v1/users_spec.rb
Add button for admin for syncing users with Slack organisation. Solution is kinda hacky, but will be used only until new fronts will be provided.
> PROP-85 Add sync users button

- README.md
Current instructions for setting up Slack application are both invalid and incomplete. This PR resolves this issue, as well as re-formats whole section to make it into as-painless-and-simple-as-possible-to-follow setup checklist.
See code comments for details re. specific parts.
> README: update and extend Slack application setup section.

- .circleci/config.yml
- docker/production/Dockerfile
- docker/staging/Dockerfile
1. Add command to install latest security updates,
2. Add `POSTGRES_HOST_AUTH_METHOD=trust` to CI.
> [BN-996] Update docker image vulnerabilities 

- config/cronotab.rb
props emails are not being sent. From logs it seems that cron is running well but the rake tasks are not being executed. The change is in loading rake tasks the same way as it is done in gems documentation.
> load rake tasks not through application
